# streamlit-only: run with `streamlit run app.py`, not `python app.py`
# genai_helper.py  -  shared by every app in this session
import os
import streamlit as st
from google import genai
from google.genai import types

MODEL_ID = "gemini-3.5-flash"

@st.cache_resource
def get_client():
    """One client, created once, shared by every rerun."""
    key = os.environ.get("GEMINI_API_KEY") or st.secrets.get("GEMINI_API_KEY")
    if not key:
        st.error("GEMINI_API_KEY is not set. Add it to .env or to Streamlit secrets.")
        st.stop()
    return genai.Client(api_key=key)

def ask(prompt, temperature=0.3, max_tokens=800, thinking=False, json_out=False):
    """One call, with every guardrail from Part A applied."""
    config = types.GenerateContentConfig(
        temperature=temperature,
        max_output_tokens=max_tokens,
        thinking_config=types.ThinkingConfig(thinking_budget=0) if not thinking else None,
        response_mime_type="application/json" if json_out else None,
    )
    response = get_client().models.generate_content(
        model=MODEL_ID, contents=prompt, config=config)

    # GUARDRAIL: response.text can be None when the budget runs out
    if response.candidates[0].finish_reason.name != "STOP":
        st.warning(f"Response was cut short ({response.candidates[0].finish_reason.name}).")
    return response.text or "", response.usage_metadata.total_token_count


# streamlit-only: run with `streamlit run app.py`, not `python app.py`
# app1_summariser.py
#import streamlit as st
#from genai_helper import ask

st.set_page_config(page_title="Summariser", page_icon="📝")
st.title("📝 Text Summariser")

text = st.text_area("Paste the text to summarise", height=250)

col1, col2 = st.columns(2)
style = col1.selectbox("Summary style",
                       ["three bullet points", "a single sentence",
                        "a paragraph for a non-technical reader"])
temperature = col2.slider("Creativity", 0.0, 1.0, 0.3, 0.1,
                          help="0.0 = same summary every time")

# --- LAYER 2: VALIDATION - reject before spending anything
MIN_CHARS, MAX_CHARS = 200, 20_000
too_short = len(text.strip()) < MIN_CHARS
too_long = len(text) > MAX_CHARS

if text and too_short:
    st.info(f"Add a little more text — {len(text.strip())} of {MIN_CHARS} characters minimum.")
if too_long:
    st.error(f"That is {len(text):,} characters. The limit is {MAX_CHARS:,}.")

if st.button("Summarise", type="primary", disabled=too_short or too_long):
    prompt = (f"Summarise the text below in {style}. "
              f"Output only the summary — no preamble, no heading.\n\n{text}")

    with st.spinner("Summarising..."):                      # LAYER 4: latency
        summary, tokens = ask(prompt, temperature=temperature)

    st.subheader("Summary")
    st.write(summary)

    c1, c2, c3 = st.columns(3)
    c1.metric("Input characters", f"{len(text):,}")
    c2.metric("Summary words", len(summary.split()))
    c3.metric("Tokens used", f"{tokens:,}")

    st.download_button("Download summary", summary, file_name="summary.txt")

st.caption("The summary is generated by a language model. It can omit or misstate "
           "details. Read the original before relying on it.")
